// Code generated by protoc-gen-go. DO NOT EDIT.
// source: wiphone.proto

package protomodel

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type Credentials struct {
	Operator string `protobuf:"bytes,1,opt,name=Operator" json:"Operator,omitempty"`
	Username string `protobuf:"bytes,2,opt,name=Username" json:"Username,omitempty"`
	Password string `protobuf:"bytes,3,opt,name=Password" json:"Password,omitempty"`
}

func (m *Credentials) Reset()                    { *m = Credentials{} }
func (m *Credentials) String() string            { return proto.CompactTextString(m) }
func (*Credentials) ProtoMessage()               {}
func (*Credentials) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{0} }

func (m *Credentials) GetOperator() string {
	if m != nil {
		return m.Operator
	}
	return ""
}

func (m *Credentials) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *Credentials) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type ConsumptionResponse struct {
	InternetTotal    int64 `protobuf:"varint,1,opt,name=InternetTotal" json:"InternetTotal,omitempty"`
	InternetConsumed int64 `protobuf:"varint,2,opt,name=InternetConsumed" json:"InternetConsumed,omitempty"`
	CallTotal        int32 `protobuf:"varint,3,opt,name=CallTotal" json:"CallTotal,omitempty"`
	CallConsumed     int32 `protobuf:"varint,4,opt,name=CallConsumed" json:"CallConsumed,omitempty"`
	RenewTime        int32 `protobuf:"varint,5,opt,name=RenewTime" json:"RenewTime,omitempty"`
}

func (m *ConsumptionResponse) Reset()                    { *m = ConsumptionResponse{} }
func (m *ConsumptionResponse) String() string            { return proto.CompactTextString(m) }
func (*ConsumptionResponse) ProtoMessage()               {}
func (*ConsumptionResponse) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{1} }

func (m *ConsumptionResponse) GetInternetTotal() int64 {
	if m != nil {
		return m.InternetTotal
	}
	return 0
}

func (m *ConsumptionResponse) GetInternetConsumed() int64 {
	if m != nil {
		return m.InternetConsumed
	}
	return 0
}

func (m *ConsumptionResponse) GetCallTotal() int32 {
	if m != nil {
		return m.CallTotal
	}
	return 0
}

func (m *ConsumptionResponse) GetCallConsumed() int32 {
	if m != nil {
		return m.CallConsumed
	}
	return 0
}

func (m *ConsumptionResponse) GetRenewTime() int32 {
	if m != nil {
		return m.RenewTime
	}
	return 0
}

type AnonymousConsumptionRequest struct {
	DeviceId    string       `protobuf:"bytes,1,opt,name=DeviceId" json:"DeviceId,omitempty"`
	Credentials *Credentials `protobuf:"bytes,2,opt,name=Credentials" json:"Credentials,omitempty"`
}

func (m *AnonymousConsumptionRequest) Reset()                    { *m = AnonymousConsumptionRequest{} }
func (m *AnonymousConsumptionRequest) String() string            { return proto.CompactTextString(m) }
func (*AnonymousConsumptionRequest) ProtoMessage()               {}
func (*AnonymousConsumptionRequest) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{2} }

func (m *AnonymousConsumptionRequest) GetDeviceId() string {
	if m != nil {
		return m.DeviceId
	}
	return ""
}

func (m *AnonymousConsumptionRequest) GetCredentials() *Credentials {
	if m != nil {
		return m.Credentials
	}
	return nil
}

func init() {
	proto.RegisterType((*Credentials)(nil), "protomodel.Credentials")
	proto.RegisterType((*ConsumptionResponse)(nil), "protomodel.ConsumptionResponse")
	proto.RegisterType((*AnonymousConsumptionRequest)(nil), "protomodel.AnonymousConsumptionRequest")
}

func init() { proto.RegisterFile("wiphone.proto", fileDescriptor2) }

var fileDescriptor2 = []byte{
	// 268 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x64, 0x91, 0x41, 0x4b, 0xc4, 0x30,
	0x10, 0x85, 0xa9, 0x75, 0xc5, 0x9d, 0x75, 0x41, 0xe2, 0xc1, 0xa2, 0x1e, 0xa4, 0x78, 0x10, 0x0f,
	0x3d, 0xe8, 0xc9, 0xa3, 0xd4, 0xcb, 0x9e, 0x94, 0xb0, 0xfe, 0x80, 0x68, 0x07, 0x2c, 0xb4, 0x33,
	0x31, 0x49, 0x2d, 0xfe, 0x42, 0xff, 0x96, 0x24, 0x21, 0xdd, 0x2d, 0x9e, 0xca, 0xfb, 0xde, 0xf0,
	0xa6, 0xf3, 0x02, 0xeb, 0xb1, 0xd5, 0x9f, 0x4c, 0x58, 0x69, 0xc3, 0x8e, 0x05, 0x84, 0x4f, 0xcf,
	0x0d, 0x76, 0xa5, 0x82, 0x55, 0x6d, 0xb0, 0x41, 0x72, 0xad, 0xea, 0xac, 0xb8, 0x80, 0xe3, 0x17,
	0x8d, 0x46, 0x39, 0x36, 0x45, 0x76, 0x9d, 0xdd, 0x2e, 0xe5, 0xa4, 0xbd, 0xf7, 0x66, 0xd1, 0x90,
	0xea, 0xb1, 0x38, 0x88, 0x5e, 0xd2, 0xde, 0x7b, 0x55, 0xd6, 0x8e, 0x6c, 0x9a, 0x22, 0x8f, 0x5e,
	0xd2, 0xe5, 0x6f, 0x06, 0x67, 0x35, 0x93, 0x1d, 0x7a, 0xed, 0x5a, 0x26, 0x89, 0x56, 0x33, 0x59,
	0x14, 0x37, 0xb0, 0xde, 0x90, 0x43, 0x43, 0xe8, 0xb6, 0xec, 0x54, 0x17, 0x16, 0xe6, 0x72, 0x0e,
	0xc5, 0x1d, 0x9c, 0x26, 0x10, 0x43, 0xb0, 0x09, 0xdb, 0x73, 0xf9, 0x8f, 0x8b, 0x2b, 0x58, 0xd6,
	0xaa, 0xeb, 0x62, 0x9a, 0xff, 0x8d, 0x85, 0xdc, 0x01, 0x51, 0xc2, 0x89, 0x17, 0x53, 0xca, 0x61,
	0x18, 0x98, 0x31, 0x9f, 0x20, 0x91, 0x70, 0xdc, 0xb6, 0x3d, 0x16, 0x8b, 0x98, 0x30, 0x81, 0xd2,
	0xc1, 0xe5, 0x13, 0x31, 0xfd, 0xf4, 0x3c, 0xd8, 0xd9, 0x45, 0x5f, 0x03, 0x5a, 0xe7, 0x4b, 0x78,
	0xc6, 0xef, 0xf6, 0x03, 0x37, 0x4d, 0x2a, 0x2f, 0x69, 0xf1, 0x38, 0xeb, 0x39, 0x5c, 0xb0, 0xba,
	0x3f, 0xaf, 0x76, 0x2f, 0x51, 0xed, 0xd9, 0x72, 0x7f, 0xf6, 0xfd, 0x28, 0x0c, 0x3d, 0xfc, 0x05,
	0x00, 0x00, 0xff, 0xff, 0x6b, 0x6e, 0xa9, 0x29, 0xc6, 0x01, 0x00, 0x00,
}
