// Code generated by protoc-gen-go. DO NOT EDIT.
// source: wiphone.proto

/*
Package protomodel is a generated protocol buffer package.

It is generated from these files:
	wiphone.proto

It has these top-level messages:
	Credentials
	UserLogin
	UseLoginResponse
	ConsumptionResponse
	AnonymousConsumptionRequest
*/
package protomodel

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Credentials struct {
	Operator string `protobuf:"bytes,1,opt,name=Operator" json:"Operator,omitempty"`
	Username string `protobuf:"bytes,2,opt,name=Username" json:"Username,omitempty"`
	Password string `protobuf:"bytes,3,opt,name=Password" json:"Password,omitempty"`
}

func (m *Credentials) Reset()                    { *m = Credentials{} }
func (m *Credentials) String() string            { return proto.CompactTextString(m) }
func (*Credentials) ProtoMessage()               {}
func (*Credentials) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Credentials) GetOperator() string {
	if m != nil {
		return m.Operator
	}
	return ""
}

func (m *Credentials) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *Credentials) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type UserLogin struct {
	Username string `protobuf:"bytes,1,opt,name=Username" json:"Username,omitempty"`
	Password string `protobuf:"bytes,2,opt,name=Password" json:"Password,omitempty"`
}

func (m *UserLogin) Reset()                    { *m = UserLogin{} }
func (m *UserLogin) String() string            { return proto.CompactTextString(m) }
func (*UserLogin) ProtoMessage()               {}
func (*UserLogin) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *UserLogin) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *UserLogin) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type UseLoginResponse struct {
	Token string `protobuf:"bytes,1,opt,name=Token" json:"Token,omitempty"`
}

func (m *UseLoginResponse) Reset()                    { *m = UseLoginResponse{} }
func (m *UseLoginResponse) String() string            { return proto.CompactTextString(m) }
func (*UseLoginResponse) ProtoMessage()               {}
func (*UseLoginResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *UseLoginResponse) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type ConsumptionResponse struct {
	InternetTotal    int64  `protobuf:"varint,1,opt,name=InternetTotal" json:"InternetTotal,omitempty"`
	InternetConsumed int64  `protobuf:"varint,2,opt,name=InternetConsumed" json:"InternetConsumed,omitempty"`
	CallTotal        int32  `protobuf:"varint,3,opt,name=CallTotal" json:"CallTotal,omitempty"`
	CallConsumed     int32  `protobuf:"varint,4,opt,name=CallConsumed" json:"CallConsumed,omitempty"`
	PeriodStart      int32  `protobuf:"varint,5,opt,name=periodStart" json:"periodStart,omitempty"`
	PeriodEnd        int32  `protobuf:"varint,6,opt,name=periodEnd" json:"periodEnd,omitempty"`
	UpdatedAt        int32  `protobuf:"varint,7,opt,name=updatedAt" json:"updatedAt,omitempty"`
	PhoneNumber      string `protobuf:"bytes,8,opt,name=phoneNumber" json:"phoneNumber,omitempty"`
}

func (m *ConsumptionResponse) Reset()                    { *m = ConsumptionResponse{} }
func (m *ConsumptionResponse) String() string            { return proto.CompactTextString(m) }
func (*ConsumptionResponse) ProtoMessage()               {}
func (*ConsumptionResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *ConsumptionResponse) GetInternetTotal() int64 {
	if m != nil {
		return m.InternetTotal
	}
	return 0
}

func (m *ConsumptionResponse) GetInternetConsumed() int64 {
	if m != nil {
		return m.InternetConsumed
	}
	return 0
}

func (m *ConsumptionResponse) GetCallTotal() int32 {
	if m != nil {
		return m.CallTotal
	}
	return 0
}

func (m *ConsumptionResponse) GetCallConsumed() int32 {
	if m != nil {
		return m.CallConsumed
	}
	return 0
}

func (m *ConsumptionResponse) GetPeriodStart() int32 {
	if m != nil {
		return m.PeriodStart
	}
	return 0
}

func (m *ConsumptionResponse) GetPeriodEnd() int32 {
	if m != nil {
		return m.PeriodEnd
	}
	return 0
}

func (m *ConsumptionResponse) GetUpdatedAt() int32 {
	if m != nil {
		return m.UpdatedAt
	}
	return 0
}

func (m *ConsumptionResponse) GetPhoneNumber() string {
	if m != nil {
		return m.PhoneNumber
	}
	return ""
}

type AnonymousConsumptionRequest struct {
	DeviceId    string       `protobuf:"bytes,1,opt,name=DeviceId" json:"DeviceId,omitempty"`
	Credentials *Credentials `protobuf:"bytes,2,opt,name=Credentials" json:"Credentials,omitempty"`
	PhoneNumber string       `protobuf:"bytes,3,opt,name=phoneNumber" json:"phoneNumber,omitempty"`
}

func (m *AnonymousConsumptionRequest) Reset()                    { *m = AnonymousConsumptionRequest{} }
func (m *AnonymousConsumptionRequest) String() string            { return proto.CompactTextString(m) }
func (*AnonymousConsumptionRequest) ProtoMessage()               {}
func (*AnonymousConsumptionRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *AnonymousConsumptionRequest) GetDeviceId() string {
	if m != nil {
		return m.DeviceId
	}
	return ""
}

func (m *AnonymousConsumptionRequest) GetCredentials() *Credentials {
	if m != nil {
		return m.Credentials
	}
	return nil
}

func (m *AnonymousConsumptionRequest) GetPhoneNumber() string {
	if m != nil {
		return m.PhoneNumber
	}
	return ""
}

func init() {
	proto.RegisterType((*Credentials)(nil), "protomodel.Credentials")
	proto.RegisterType((*UserLogin)(nil), "protomodel.UserLogin")
	proto.RegisterType((*UseLoginResponse)(nil), "protomodel.UseLoginResponse")
	proto.RegisterType((*ConsumptionResponse)(nil), "protomodel.ConsumptionResponse")
	proto.RegisterType((*AnonymousConsumptionRequest)(nil), "protomodel.AnonymousConsumptionRequest")
}

func init() { proto.RegisterFile("wiphone.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 357 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x92, 0xc1, 0x4e, 0xe3, 0x30,
	0x10, 0x86, 0x95, 0x66, 0xdb, 0x6d, 0xa7, 0x5b, 0xa9, 0xf2, 0xae, 0xb4, 0x11, 0x70, 0xa8, 0x22,
	0x0e, 0x15, 0x87, 0x1e, 0xe0, 0xc4, 0xb1, 0x0a, 0x1c, 0x2a, 0x21, 0x40, 0xa1, 0x7d, 0x00, 0x17,
	0x8f, 0x20, 0x22, 0xf1, 0x04, 0xdb, 0xa1, 0xe2, 0x45, 0x78, 0x07, 0xde, 0x12, 0xd9, 0x26, 0x69,
	0xd3, 0x4a, 0x9c, 0xaa, 0xff, 0xff, 0xa7, 0x9f, 0x27, 0x33, 0x03, 0xa3, 0x4d, 0x56, 0x3e, 0x93,
	0xc4, 0x59, 0xa9, 0xc8, 0x10, 0x03, 0xf7, 0x53, 0x90, 0xc0, 0x3c, 0xe6, 0x30, 0x4c, 0x14, 0x0a,
	0x94, 0x26, 0xe3, 0xb9, 0x66, 0x47, 0xd0, 0xbf, 0x2b, 0x51, 0x71, 0x43, 0x2a, 0x0a, 0x26, 0xc1,
	0x74, 0x90, 0x36, 0xda, 0x66, 0x2b, 0x8d, 0x4a, 0xf2, 0x02, 0xa3, 0x8e, 0xcf, 0x6a, 0x6d, 0xb3,
	0x7b, 0xae, 0xf5, 0x86, 0x94, 0x88, 0x42, 0x9f, 0xd5, 0x3a, 0x4e, 0x60, 0x60, 0xeb, 0x6e, 0xe8,
	0x29, 0x93, 0x2d, 0x48, 0xf0, 0x03, 0xa4, 0xb3, 0x07, 0x99, 0xc2, 0x78, 0xa5, 0xd1, 0x31, 0x52,
	0xd4, 0x25, 0x49, 0x8d, 0xec, 0x1f, 0x74, 0x97, 0xf4, 0x82, 0xf2, 0x1b, 0xe4, 0x45, 0xfc, 0xd9,
	0x81, 0xbf, 0x09, 0x49, 0x5d, 0x15, 0xa5, 0xc9, 0x68, 0x5b, 0x7d, 0x0a, 0xa3, 0x85, 0x34, 0xa8,
	0x24, 0x9a, 0x25, 0x19, 0x9e, 0xbb, 0x7f, 0x85, 0x69, 0xdb, 0x64, 0x67, 0x30, 0xae, 0x0d, 0x0f,
	0x41, 0xdf, 0x4b, 0x98, 0x1e, 0xf8, 0xec, 0x04, 0x06, 0x09, 0xcf, 0x73, 0x4f, 0xb3, 0x5f, 0xdd,
	0x4d, 0xb7, 0x06, 0x8b, 0xe1, 0x8f, 0x15, 0x0d, 0xe5, 0x97, 0x2b, 0x68, 0x79, 0x6c, 0x02, 0xc3,
	0x12, 0x55, 0x46, 0xe2, 0xc1, 0x70, 0x65, 0xa2, 0xae, 0x2b, 0xd9, 0xb5, 0xec, 0x1b, 0x5e, 0x5e,
	0x4b, 0x11, 0xf5, 0xfc, 0x1b, 0x8d, 0x61, 0xd3, 0xaa, 0x14, 0xdc, 0xa0, 0x98, 0x9b, 0xe8, 0xb7,
	0x4f, 0x1b, 0xc3, 0xd1, 0xed, 0xda, 0x6f, 0xab, 0x62, 0x8d, 0x2a, 0xea, 0xbb, 0x29, 0xed, 0x5a,
	0xf1, 0x47, 0x00, 0xc7, 0x73, 0x49, 0xf2, 0xbd, 0xa0, 0x4a, 0xb7, 0x86, 0xf6, 0x5a, 0xa1, 0x36,
	0x76, 0x23, 0x57, 0xf8, 0x96, 0x3d, 0xe2, 0x42, 0xd4, 0xdb, 0xaa, 0x35, 0xbb, 0x6c, 0x5d, 0x8e,
	0x1b, 0xd2, 0xf0, 0xfc, 0xff, 0x6c, 0x7b, 0x5b, 0xb3, 0x9d, 0x38, 0x6d, 0x5d, 0xd9, 0x5e, 0x63,
	0xe1, 0x41, 0x63, 0xeb, 0x9e, 0xc3, 0x5c, 0x7c, 0x05, 0x00, 0x00, 0xff, 0xff, 0x93, 0x6f, 0x58,
	0xb1, 0xba, 0x02, 0x00, 0x00,
}
